// ─── DB row shapes for ai_conversations and ai_messages ──────────────────────
// These mirror the Supabase table columns exactly.
// They are intentionally separate from aiPlannerTypes so the planning engine
// has no dependency on the persistence layer.

import type { AIResponse, PlannerContext } from './aiPlannerTypes';

// ─── ai_conversations row ─────────────────────────────────────────────────────
export interface ConversationRow {
  id:              string;       // UUID
  user_id:         string;       // UUID — auth.users.id
  title:           string;
  context_summary: PlannerContext | null;
  last_active_at:  string;       // ISO-8601
  created_at:      string;       // ISO-8601
  is_pinned:       boolean;
  is_archived:     boolean;
  is_favorite:     boolean;
}

// ─── ai_messages row ──────────────────────────────────────────────────────────
export interface MessageRow {
  id:              string;       // UUID
  conversation_id: string;       // UUID → ai_conversations.id
  user_id:         string;       // UUID
  role:            'user' | 'assistant';
  content:         string;
  ai_response:     AIResponse | null;
  created_at:      string;       // ISO-8601
}

// ─── Insert shapes (id/created_at generated by DB) ───────────────────────────
export type ConversationInsert = Omit<ConversationRow, 'id' | 'created_at'>;
export type MessageInsert      = Omit<MessageRow,      'id' | 'created_at'>;

// ─── Update shapes ────────────────────────────────────────────────────────────
export interface ConversationUpdate {
  title?:           string;
  context_summary?: PlannerContext;
  last_active_at?:  string;
  is_pinned?:       boolean;
  is_archived?:     boolean;
  is_favorite?:     boolean;
}
