import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Camera, Check, ShoppingCart, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export default function PhotographerPackages({ provider, profile }: { provider: any; profile: any }) {
  const { user } = useAuth(); const nav = useNavigate(); const qc = useQueryClient(); const [selected, setSelected] = useState<Record<string, string[]>>({}); const [detail, setDetail] = useState<any>(null); const [busy, setBusy] = useState<string | null>(null);
  const { data: rows = [], isLoading } = useQuery({ queryKey: ['public-photography-packages', provider.id], queryFn: async () => { const { data, error } = await supabase.from('photography_packages' as any).select('*, photography_package_images(*), photography_package_highlights(*), photography_package_addons(*)').eq('photographer_id', provider.id).eq('is_active', true).eq('is_visible', true).eq('status', 'published').order('created_at'); if (error) throw error; return data ?? []; } });
  useEffect(() => { const channel = supabase.channel(`public-photography-${provider.id}`).on('postgres_changes', { event: '*', schema: 'public', table: 'photography_packages', filter: `photographer_id=eq.${provider.id}` }, () => qc.invalidateQueries({ queryKey: ['public-photography-packages', provider.id] })).on('postgres_changes', { event: '*', schema: 'public', table: 'photography_package_images' }, () => qc.invalidateQueries({ queryKey: ['public-photography-packages', provider.id] })).subscribe(); return () => { supabase.removeChannel(channel); }; }, [provider.id]);
  const add = async (p: any, checkout = false) => { if (!user) { toast.error('Please log in to continue'); nav('/auth'); return; } setBusy(p.id); const { data: cartId, error } = await supabase.rpc('add_photography_cart_item' as any, { p_package_id: p.id, p_addon_ids: selected[p.id] ?? [] }); setBusy(null); if (error) { toast.error(error.message); return; } sessionStorage.setItem('vowza_photography_checkout', JSON.stringify({ cartId, providerName: profile.full_name })); toast.success(checkout ? 'Ready for secure checkout.' : 'Added to your photography cart.'); if (checkout) nav('/checkout?photography=1'); };
  if (isLoading) return <div className="h-48 animate-pulse rounded-2xl bg-muted" />;
  if (!rows.length) return <div className="rounded-2xl border bg-surface-1 p-10 text-center text-sm text-muted-foreground">This photographer has not published packages yet.</div>;
  return <div className="space-y-5"><div><h2 className="text-xl font-bold">Photography Packages</h2><p className="text-sm text-muted-foreground">Compare coverage, deliverables, albums and travel before booking.</p></div><div className="grid gap-4 md:grid-cols-2">{rows.map((p: any) => <PackageCard key={p.id} p={p} selected={selected[p.id] ?? []} setSelected={(ids: string[]) => setSelected(value => ({ ...value, [p.id]: ids }))} view={() => setDetail(p)} add={() => add(p)} book={() => add(p, true)} busy={busy === p.id} />)}</div>{detail && <Detail p={detail} close={() => setDetail(null)} add={() => add(detail)} book={() => add(detail, true)} busy={busy === detail.id} />}</div>;
}
function PackageCard({ p, selected, setSelected, view, add, book, busy }: any) { const image = p.photography_package_images?.find((x: any) => x.is_cover) ?? p.photography_package_images?.[0]; const extra = (p.photography_package_addons ?? []).filter((a: any) => selected.includes(a.id)).reduce((total: number, a: any) => total + Number(a.price), 0); return <div className="overflow-hidden rounded-2xl border border-border/60 bg-surface-1"><div className="h-44 bg-secondary">{image ? <img src={image.public_url} alt={p.name} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><Camera className="text-muted-foreground" /></div>}</div><div className="p-5"><div className="flex justify-between gap-3"><h3 className="font-bold">{p.name}</h3><b>₹{Number(p.price).toLocaleString('en-IN')}</b></div><p className="mt-1 text-xs text-muted-foreground">{p.photography_type || 'Photography'} · {p.duration} · {p.team_size_custom || p.team_size || 1} member team</p><p className="mt-2 text-xs text-muted-foreground">{p.edited_photos ? `${p.edited_photos} edited photos` : 'Edited photos included'}{p.raw_photos_included ? ' · Raw files included' : ''}</p>{p.description && <p className="mt-3 text-sm text-muted-foreground">{p.description}</p>}<ul className="mt-3 space-y-1">{(p.photography_package_highlights ?? []).slice(0, 3).map((h: any) => <li key={h.id} className="text-xs"><Check className="mr-1 inline h-3 text-emerald-600" />{h.text}</li>)}</ul><div className="mt-4 space-y-2">{(p.photography_package_addons ?? []).filter((a: any) => a.is_active).map((a: any) => <label key={a.id} className="flex items-center justify-between rounded-lg bg-secondary p-2 text-xs"><span><input type="checkbox" checked={selected.includes(a.id)} onChange={() => setSelected(selected.includes(a.id) ? selected.filter((id: string) => id !== a.id) : [...selected, a.id])} /><span className="ml-2">{a.name}</span></span><b>+₹{Number(a.price).toLocaleString('en-IN')}</b></label>)}</div><div className="mt-5 grid grid-cols-3 gap-2"><button onClick={view} className="rounded-xl border py-2 text-xs font-semibold">View Details</button><button disabled={busy} onClick={add} className="rounded-xl border border-[#8B1538] py-2 text-xs font-semibold text-[#8B1538]"><ShoppingCart className="mr-1 inline h-3" />Add to Cart</button><button disabled={busy} onClick={book} className="rounded-xl bg-[#8B1538] py-2 text-xs font-semibold text-white">{busy ? 'Adding…' : `Book Now${extra ? ` · ₹${(Number(p.price) + extra).toLocaleString('en-IN')}` : ''}`}</button></div></div></div>; }
function Detail({ p, close, add, book, busy }: any) { const image = p.photography_package_images?.find((x: any) => x.is_cover) ?? p.photography_package_images?.[0]; return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white"><div className="relative h-56 bg-secondary">{image && <img src={image.public_url} alt={p.name} className="h-full w-full object-cover" />}<button onClick={close} className="absolute right-3 top-3 rounded-full bg-white p-2"><X className="h-4" /></button></div><div className="space-y-4 p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{p.name}</h2><p className="text-sm text-muted-foreground">{p.photography_type} · {p.duration}</p></div><b>₹{Number(p.price).toLocaleString('en-IN')}</b></div>{p.description && <p className="text-sm text-muted-foreground">{p.description}</p>}<div className="grid grid-cols-2 gap-3 rounded-xl bg-secondary p-3 text-sm"><span>Team: {p.team_size_custom || p.team_size || 1}</span><span>Delivery: {p.delivery_time || 'On request'}</span><span>Edited: {p.edited_photos ?? 'Included'}</span><span>Raw files: {p.raw_photos_included ? 'Included' : 'Not included'}</span>{p.album_included && <span>Album: {p.album_type || 'Included'} {p.album_size && `(${p.album_size})`}</span>}{p.travel_included && <span>Travel: {p.travel_radius_km ?? 0} km included</span>}</div><ul className="space-y-2">{(p.photography_package_highlights ?? []).map((h: any) => <li key={h.id} className="text-sm"><Check className="mr-2 inline h-4 text-emerald-600" />{h.text}</li>)}</ul><div className="grid grid-cols-2 gap-3"><button disabled={busy} onClick={add} className="rounded-xl border border-[#8B1538] py-3 text-sm font-semibold text-[#8B1538]">Add to Cart</button><button disabled={busy} onClick={book} className="rounded-xl bg-[#8B1538] py-3 text-sm font-semibold text-white">Book Now</button></div></div></div></div>; }
